### ISSUE TITLE
[Feature Request] Option to disable the enchantment glint added by this mod

### ISSUE THREAD

**Issue by Abbanon** [Bernasss12/BetterEnchantedBooks#19]
I've noticed this mod adds an extra layer of enchantment glint *on top* of the default enchantment glint layer, making it appear much more opaque and harder to see the book texture underneath. 
It's even more obscured when you're using resource packs with custom enchantment glint textures.
Any way we could have a toggle to disable the extra glint layer this mod adds to the enchanted books?

**Comment by Bernasss12** [comment]
Could you please show what you mean with extra layer and more obscure? All the mod does is add a different glint texture just like a texture pack would, and in case a texture pack does change the glint it's supposed to override it

**Comment by Abbanon** [comment]
I'm unable to get it in motion, but here's some screenshots I've taken.
Left is an enchanted book from this mod, and right is a regular written book.
The enchantment glint on books from this mod is much more bright and opaque compared to normal, almost like it's applying the texture more than once. 
It also moves in a bit of a different pattern compared to regular.
(Edit: This is with a custom enchantment glint texture)
![2020-11-05_11 54 36](https://user-images.githubusercontent.com/37251822/98271700-34505980-1f5e-11eb-98c3-a01141691901.png)
![2020-11-05_11 54 39](https://user-images.githubusercontent.com/37251822/98271702-34e8f000-1f5e-11eb-93dc-4ac180251f7e.png)
![2020-11-05_11 54 13](https://user-images.githubusercontent.com/37251822/98272340-fc95e180-1f5e-11eb-960d-685af54d7690.png)

**Comment by Bernasss12** [comment]
That doesn't look like the going that ships with my mod actually, are you sure that happens without the resource pack active? I'm lookin into it but the "custom" glint is really just a texture and the rest is just vanilla

**Comment by Abbanon** [comment]
I can confirm it happens with vanilla textures as well.
![2020-11-05_12 06 16](https://user-images.githubusercontent.com/37251822/98272765-71691b80-1f5f-11eb-9d58-8d49ce05266f.png)
![2020-11-05_12 06 30](https://user-images.githubusercontent.com/37251822/98272766-7201b200-1f5f-11eb-95f4-558e981628f7.png)
![2020-11-05_12 09 30](https://user-images.githubusercontent.com/37251822/98273041-d0c72b80-1f5f-11eb-9a56-db65922ab519.png)
![2020-11-05_12 17 32](https://user-images.githubusercontent.com/37251822/98274016-edb02e80-1f60-11eb-951f-61e5d9972cf6.png)

**Comment by Abbanon** [comment]
I managed to record some videos of the animations in progress on the hotbar. Hope it helps to convey what's going on.
[example videos.zip](https://github.com/Bernasss12/BetterEnchantedBooks/files/5496062/example.videos.zip)

**Comment by Bernasss12** [comment]
Can you tell me which version of the mod you are using?

**Comment by FewerFlaws** [comment]
I would also like an option to disable the enchantment glint.  I've already got glints disabled on potions, and I think it's conceptually consistent for a dormant enchantment in a book to have no glint compared to an active enchantment on equipment.

**Comment by Abbanon** [comment]
> Can you tell me which version of the mod you are using?

It's been happening for the last two or three versions, back when I first started using this mod. 
Still occurs on the latest (v1.1.4)

Weird double-layered glint issue aside, it would be nice to be able to toggle the custom glint brought by this mod on/off.
I'm using a mod that disables the Enchanted Book glint entirely, and I only use this mod for the colour customization.
I'd rather have the choice of using the vanilla glint texture.

**Comment by Bernasss12** [comment]
As of the latest CurseForge release there is now an option to disable the glint on the enchanted books. Thanks for the feedback and sorry it took s long to finally come around to doing it.

**Comment by Bernasss12** [comment]
I believe this should have fixed this issue, if not please feel free to reopen it or to open a new one.
