### ISSUE TITLE
[Bug] REI does not display tooltips for enchanted books

### ISSUE THREAD

**Issue by FewerFlaws** [Bernasss12/BetterEnchantedBooks#20]
**Describe the bug**
This removes all tooltips from enchanted books in the REI interface.

**To Reproduce**
Install this mod as well as Roughly Enough Items.  Type #book into the REI search bar.  Mouse over the enchanted books.

**Expected behavior**
The tooltips from this mod should show when mousing over enchanted books in the REI interface.

**Please include:**
 - Minecraft Version: 1.16.4
 - Mod Version: 1.1.4
 - REI Version: 5.8.9

**Comment by Bernasss12** [comment]
Still haven't been able to figure out what's causing this

**Comment by FewerFlaws** [comment]
It's not a particularly reliable bug either.  In my modpack test environment I'm running enchantment descriptions and enchantment lore as well.  The REI descriptions will show for a while after a reset, but after some enchantment testing (grabbing books through REI, applying enchants to items through anvil, using enchanted items) the descriptions will disappear.

This suggests to me that it's something that runs after initialization.

**Comment by Bernasss12** [comment]
Yeah I got it happening semi-reliably but I can't see where the issue actually lies. What did happen in my case and I'd like feedback in case that's happening for anyone else, was after doing the same steps that make the tool tip stop working the icon rendering on normal tool tips also broke.

**Comment by FewerFlaws** [comment]
Let me know the precise process you're using to trigger the bug and I'll see if I can help =]

**Comment by FewerFlaws** [comment]
Might be worth it to ask shedaniel for insights as well.
