### ISSUE TITLE
[Feature Request] Show maximum enchantment level in tooltip

### ISSUE THREAD

**Issue by maxsupermanhd** [Bernasss12/BetterEnchantedBooks#21]
Sometimes I just forget what's maximum level of enchantment, will be nice to have it in tooltip. Bet that's easy to make

**Comment by Bernasss12** [comment]
How would you do something like that?
Like `Sharpness III/V`?
Could you please be more expressive about what you had in mind?

**Comment by maxsupermanhd** [comment]
Yeah, something like `III/V` will do perfectly fine. Actually any format will do, even `... III (max IV)`. It's up to you mostly, I just want it to be more accessible like so I can get this information from game itself without spending time getting second book or trying to level up maxed out enchantment. As I remember there is no way in default Minecraft to get max level information, only trip to the wiki...

PS I'm happy that you are alive, great mod, I enjoy it, thank you

**Comment by Bernasss12** [comment]
Well thank you for that!
I thought I had it all done but I guess this is a weird side-effect of how I tried to do it :)
![image](https://user-images.githubusercontent.com/6233500/107274625-8bc40100-6a48-11eb-8aea-07550443cd6b.png)
 I should have this fixed within the next hour

**Comment by Bernasss12** [comment]
Done
![image](https://user-images.githubusercontent.com/6233500/107277035-caa78600-6a4b-11eb-9562-b908d0e62454.png)

**Comment by Bernasss12** [comment]
It's supposed to work with any added enchantments just like any other of my mod's features.

**Comment by Bernasss12** [comment]
This is technically done but I guess maybe I should add an option where either the whole name is colored different if it at max level or the max level isn't shown in case the enchantment _already is at max level_ or both maybe idk.

But that's a problem for the future, anyway, hope you enjoy the new feature! (it's disabled by default so you will need to change the settings for the mod)

**Comment by maxsupermanhd** [comment]
Thank you, I appreciate your work man.

As I understood from your messages here (not really understanding this mixin and stuff in java) it will detect available enchantments in game and get info about them or they are just yeet-hardcoded? (hope not)

**Comment by Bernasss12** [comment]
Yeah everything should work with added enchantments. The only thing that is hard coded, and that I do plan to make configurable, is the list of items/icons that show on the tooltip.
Every enchantment and the items they can be applied to are calculated at runtime and so it _should_ work with any mods that add enchantments without any additional setup.
