### ISSUE TITLE
[Bug] Items glitching out in big books

### ISSUE THREAD

**Issue by JoshuaVandaele** [Bernasss12/BetterEnchantedBooks#23]
**Describe the bug**
[image](https://user-images.githubusercontent.com/24195176/107714756-1a957f80-6cce-11eb-8394-36daa6189036.png)

**To Reproduce**
Book with lots of enchants

**Please include:**
 - Minecraft Version: 1.16.5
 - Mod Version 1.2.2

**Comment by Bernasss12** [comment]
Thank you for reporting this! It will be fixed on release 1.2.3.
![image](https://user-images.githubusercontent.com/6233500/107724458-ce513c00-6cdb-11eb-9e7c-70594967fc79.png)
