### ISSUE TITLE
[Feature Request] Show max enchantment level in enchanting table too

### ISSUE THREAD

**Issue by maxsupermanhd** [Bernasss12/BetterEnchantedBooks#25]
Not long ago you implemented maximum level of enchantment in tooltip, it will be great to have it in enchanting table too.

**Comment by Bernasss12** [comment]
Funnily enough I went out of my way to avoid that :thinking:
I guess I could work it in anyways.

**Comment by maxsupermanhd** [comment]
Any news?

**Comment by Bernasss12** [comment]
Only took 3 years or so but it's here.

![image](https://github.com/Bernasss12/BetterEnchantedBooks/assets/6233500/cc4c7fe8-cf82-43c6-a7b0-646345cf01b7)
