### ISSUE TITLE
[Bug] Division by 0 crash when drawing tooltip with "none" sorting mode

### ISSUE THREAD

**Issue by LemmaEOF** [Bernasss12/BetterEnchantedBooks#27]
In some circumstances, the game can divide by zero when attempting to draw tooltips for unenchanted but enchantable items while on a sorting mode of none.

Originally occurred when shift-clicking a pair of unenchanted books into the crafting table

Minecraft: 1.16.5
BEBooks: 1.2.4

[Crash log link](https://gist.githubusercontent.com/natanfudge/ab841ec633fad44612ad47e694318965/raw/8d1e843cc5b633b5c60a3d946b4985fa71407f73/crash.txt)

**Comment by Bernasss12** [comment]
Thank you for the report! Hopefully this will prevent that issue from happening anymore, at least until I refactor the whole mod.
I'm hoping to change everything soon.
