### ISSUE TITLE
[Bug] Plz add low Ench-glint back

### ISSUE THREAD

**Issue by Ruangfafa** [Bernasss12/BetterEnchantedBooks#28]
Really want the one before, less ench-glint but not totaly gone, and also for other items but not just books.

**Comment by Bernasss12** [comment]
You can do that by installing a simple resource pack

**Comment by maxsupermanhd** [comment]
Confirmed, enchantment flint looks different and no way to turn it back to how it was before. However I am already comfortable with new one...

**Comment by Bernasss12** [comment]
This is not an issue and can be done externally and this feature is not within the scope of a mod in my opinion since it is simply a change of vanilla resources.
