### ISSUE TITLE
[Feature Request] Please rename your mixin methods

### ISSUE THREAD

**Issue by SilverAndro** [Bernasss12/BetterEnchantedBooks#29]
Hi, your mod is causing a crash with my mod when I try to grab tool tips of items, but all the mixins appear as stuff like `handler$kadwn$method17869Tail` in the crash log which is completely useless

Could you rename your mixin methods to be what the mixin does and not where it is? Thanks

**Comment by Bernasss12** [comment]
The mixin you are looking for is [here](https://github.com/Bernasss12/BetterEnchantedBooks/blob/mc-1.16.4/src/main/java/dev/bernasss12/bebooks/mixin/ItemStackMixin.java#L64)

I'm probably not changing any of the code until I do a full mod rewrite so just feel free to ask me what each method does.

**Comment by SilverAndro** [comment]
I was able to find it and can mostly tell what it does, its just that without the ability to attribute mixins to JARs or at least have a good guess, it can be nigh-impossible to actually get bug reports to you

**Comment by Bernasss12** [comment]
That's true and I understand what you mean but I still don't think I will revisit this code at the moment. I'm focusing on another project at the moment and the code base is too different for me to be hopping back and forth.
