### ISSUE TITLE
[Crash] Held Item Info mod + any Tooltip Sorting Mode

### ISSUE THREAD

**Issue by Felix14-v2** [Bernasss12/BetterEnchantedBooks#32]
Opening any GUI with enabled tooltip sorting causes a crash.

**To Reproduce**
• Launch minecraft with [BetterEnchantedBooks](https://www.curseforge.com/minecraft/mc-mods/better-enchanted-books) and [Held Item Info](https://www.curseforge.com/minecraft/mc-mods/held-item-info) mods
• Make sure that any type of tooltip sorting is enabled
• Enchant any item
• Take the item in your hand
• Open any GUI
• Get crash

Logs:
[crash-2021-04-28_02.39.30-client.txt](https://github.com/Bernasss12/BetterEnchantedBooks/files/6388207/crash-2021-04-28_02.39.30-client.txt)
[latest.log](https://github.com/Bernasss12/BetterEnchantedBooks/files/6388208/latest.log)

**Comment by Bernasss12** [comment]
Version 1.2.8 is supposed to fix it, I tested it lightly but please if the problem persists on your end please reopen the issue.
