### ISSUE TITLE
[Crash] Enchant Book Item (no enchantment attached)

### ISSUE THREAD

**Issue by MissGamerz** [Bernasss12/BetterEnchantedBooks#33]
**Describe the bug**
A Hard Crash of minecraf based upon your tooltip for enchantments, the tooltip for showing what a enchantment can be applied to still seems to try to work if a enchantedbook with no enchantment data is in a Inventory the player opens. This can be aquired with (/give {name} enchanted_book 1) OR is sometimes used in custom GUIS on servers for click GUI Menus.

**To Reproduce**
i managed to come across this whilst on my network running yatopia (a paper spigot fork) 1.16.5 whilst using the plugin customcrafting(it has a GUI configurator for making custom recipes and items in game and injects them on the fly) in customcraftings item creator page there is a enchantment book which has no enchantment data on it. this will crash the client.

**Expected behavior**
it should not crash???????? and just treat the enchantment book as if it a normal item

**Comment by Bernasss12** [comment]
Well I don't personally agree with your assessment of the expected behaviour since an _enchanted book_ is supposed to have at least one _enchantment_ but alas this will be a quick fix so expect it within a day hopefully.

**Comment by MissGamerz** [comment]
sorry i was trying to be funny, wasnt meant to be taken bad. but yea a catch for this and make the tooltip thing ignore it should fix this is quite common tbh in Custm GUIs on servers such as hypixel have them and so on and contain the enchantment book without NBT data

**Comment by Bernasss12** [comment]
I didn't take it badly don't worry about it.
Can you try to get me a log thought? I can't seem to reproduce the issue on my pc.
(only really tried with the /give command)

**Comment by MissGamerz** [comment]
il will try there is going to be delay as we moves our networks node and database so sorry for any delay with this

**Comment by Bernasss12** [comment]
Can you pleased test this again with the newest build? PR #34 Might've fixed it.

**Comment by MissGamerz** [comment]
this is fixed sorry for delay ive been away from github
