### ISSUE TITLE
1.17.1 Better Enchanted Books?

### ISSUE THREAD

**Issue by CallMehKing** [Bernasss12/BetterEnchantedBooks#43]
Can We Have 1.17.1 Better Enchanted Books Pls? I Really Love The Mod

**Comment by fgardt** [comment]
#37 has been merged already but no version is released thus far.
You can try the unofficial beta for 1.17 from the author of #37 from [here](https://github.com/Fourmisain/BetterEnchantedBooks/releases/tag/1.2.9).

**Comment by alexmozaidze** [comment]
The 1.17.1 version is already out

**Comment by triphora** [comment]
It appears to be released on Curse, but not on Modrinth.

**Comment by Bernasss12** [comment]
Version 1.2.12 was just released on CF and Modrinth, hope everyone enjoys.
Report any bugs you come across :)
