### ISSUE TITLE
[Bug] CIT Resewn mod incompatibility (I think)

### ISSUE THREAD

**Issue by alexmozaidze** [Bernasss12/BetterEnchantedBooks#45]
**Describe the bug**
The books that should've had a different texture look very broken to the point I barely can call them books, books that weren't changed (mainly modded ones) weren't affected by this bug. Tested with _Xali's Enchanted Books_ resourcepack

**Steps To Reproduce**
1. Install [CIT Resewn](https://www.curseforge.com/minecraft/mc-mods/cit-resewn) along with BetterEnchantedBooks
2. Put [Xali's Enchanted Books](https://www.curseforge.com/minecraft/texture-packs/xalis-enchanted-books) into the resourcepacks directory
3. Activate the resourcepack
4. Look at the books, they look horrible!

**Expected behavior**
BetterEnchantedBooks should not have changed the books that were retextured

**Screenshots**
The three books on the bottom that look correct are the modded ones and weren't touched by the resourcepack
![2021-09-19_20 08 34](https://user-images.githubusercontent.com/51371527/133934640-72ddd704-e815-40a8-83c4-d5368002fb3b.png)

**Please include:**
 - Minecraft Version: 1.17.1
 - Mod Version: 1.2.10
 - Dependencies or other mod's versions: CIT Resewn 0.5.3

**Comment by Bernasss12** [comment]
Could you try changing the settings of the mod? Disabling the colouring options for example? I would have to look into the CIT mod to deduce what to do and what could be conflicting.

**Comment by alexmozaidze** [comment]
I disabled coloring. Books, unfortunately, look as messed up, except that they are now one color
![2021-09-20_15 21 02](https://user-images.githubusercontent.com/51371527/133997604-52801af8-b7e8-418f-ac85-d56c0ab53fbd.png)

**Comment by Bernasss12** [comment]
So the only thing I can try to do is to change the way I'm coloring the strips, currently I'm applying a tint to every layer above layer0, I should really only be doing that to layer1.
Other than that there's nothing I can do since CITResewn alters a lot of the loaded models to a degree I don't really fully compreend. So chances are this will not fix it but there's really not much I can think of to do so.

**Comment by Boobies** [comment]
Why is anything happening at all when coloring is disabled, though?

**Comment by Bernasss12** [comment]
The coloring is something registered in fabric api at startup, when it's turned off it just sets the original book color. CIT resewn is changing the layer order making the colored layer (unused in vanilla) have the whole book texture

**Comment by Boobies** [comment]
Perhaps not use the mixin at all when CIT Resewn is present?

**Comment by Bernasss12** [comment]
I'm going to call this a mod incompatibility for the time being with a chance of being fixed in the future, but not by "not working if x-mod is present"
