### ISSUE TITLE
Modrinth not up to date

### ISSUE THREAD

**Issue by triphora** [Bernasss12/BetterEnchantedBooks#55]
I noticed that the [Modrinth releases](https://modrinth.com/mod/better-enchanted-books) aren't up-to-date with the [CurseForge releases](https://curseforge.com/project/369122) (specifically in regards to 1.18 and 1.19). Could you keep the Modrinth releases up to date?

If you'd like, you can even set up [Minotaur](https://github.com/modrinth/minotaur) or [mc-publish](https://github.com/Kir-Antipov/mc-publish) to automate build publishing.

**Comment by Bernasss12** [comment]
I'm sorry I've just been so away that I forgot about it, I will publish it now, thanks for reminding me
