### ISSUE TITLE
[Bug] v1.4.2 crashes on 1.19.2

### ISSUE THREAD

**Issue by ihatecsv** [Bernasss12/BetterEnchantedBooks#61]
![image](https://github.com/Bernasss12/BetterEnchantedBooks/assets/9065758/869b8cee-de6c-4e66-8ed8-71a214bf27ed)

On Modrinth, `v1.4.2` is listed to support `1.19` to `1.19.4`, but it crashes on `1.19.2`. `v1.4.1` works as expected on `1.19.2`.

**Comment by Bernasss12** [comment]
Changed the supported versions as mentioned by you. Version 1.4.2 now should only be set as compatible with mc1.19.3 and mc1.19.4.
