### ISSUE TITLE
1.20.6

### ISSUE THREAD

**Issue by PukPukov** [Bernasss12/BetterEnchantedBooks#69]

**Comment by Bernasss12** [comment]
I did a good bit of work on converting the kotlin version of the mod to 1.20.5 but currently I don't have time to finish it and some things are still iffy.

1.20.6 will eventually happen but it's not a priority for me at the moment.

**Comment by Bernasss12** [comment]
Get it now while it's hot!!

https://modrinth.com/mod/better-enchanted-books/version/2.0.4-beta
https://www.curseforge.com/minecraft/mc-mods/better-enchanted-books/files/5331185
