### ISSUE TITLE
mods are ganging up on each other

### ISSUE THREAD

**Issue by POGI-dev0110** [Bernasss12/BetterEnchantedBooks#71]
i have this mod called highlighter, it was for fabric. im dropping that mod anyway but im curious as to why they are ganging up on each other. i hope i can get a feedback as soon as you can. i'll state the full details of the crash below.

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2024-06-07 21:56:55
Description: Rendering screen

java.lang.NoClassDefFoundError: net/minecraft/class_8828$class_2585
	at dev.bernasss12.bebooks.util.text.IconTooltipDataText.method_10851(IconTooltipDataText.java:23)
	at net.minecraft.class_2561.method_27658(class_2561.java:95)
	at net.minecraft.class_5223.method_27476(class_5223.java:128)
	at net.minecraft.class_5225.method_27488(class_5225.java:47)
	at net.minecraft.class_327.method_27525(class_327.java:314)
	at com.anthonyhilyard.iceberg.util.Tooltips.lambda$gatherTooltipComponents$2(Tooltips.java:363)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at com.anthonyhilyard.iceberg.util.Tooltips.lambda$gatherTooltipComponents$4(Tooltips.java:360)
	at java.base/java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:214)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.IntPipeline.reduce(IntPipeline.java:520)
	at java.base/java.util.stream.IntPipeline.max(IntPipeline.java:483)
	at com.anthonyhilyard.iceberg.util.Tooltips.gatherTooltipComponents(Tooltips.java:376)
	at com.anthonyhilyard.iceberg.util.Tooltips.gatherTooltipComponents(Tooltips.java:339)
	at net.minecraft.class_332.handler$cgk000$iceberg$renderTooltip(class_332.java:2330)
	at net.minecraft.class_332.method_51437(class_332.java:601)
	at net.minecraft.class_465.method_2380(class_465.java:178)
	at com.tom.storagemod.gui.AbstractStorageTerminalScreen.method_25394(AbstractStorageTerminalScreen.java:389)
	at com.tom.storagemod.gui.CraftingTerminalScreen.method_25394(CraftingTerminalScreen.java:130)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_8828$class_2585
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 31 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dev.bernasss12.bebooks.util.text.IconTooltipDataText.method_10851(IconTooltipDataText.java:23)
	at net.minecraft.class_2561.method_27658(class_2561.java:95)
	at net.minecraft.class_5223.method_27476(class_5223.java:128)
	at net.minecraft.class_5225.method_27488(class_5225.java:47)
	at net.minecraft.class_327.method_27525(class_327.java:314)
	at com.anthonyhilyard.iceberg.util.Tooltips.lambda$gatherTooltipComponents$2(Tooltips.java:363)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at com.anthonyhilyard.iceberg.util.Tooltips.lambda$gatherTooltipComponents$4(Tooltips.java:360)
	at java.base/java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:214)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.IntPipeline.reduce(IntPipeline.java:520)
	at java.base/java.util.stream.IntPipeline.max(IntPipeline.java:483)
	at com.anthonyhilyard.iceberg.util.Tooltips.gatherTooltipComponents(Tooltips.java:376)
	at com.anthonyhilyard.iceberg.util.Tooltips.gatherTooltipComponents(Tooltips.java:339)
	at net.minecraft.class_332.handler$cgk000$iceberg$renderTooltip(class_332.java:2330)
	at net.minecraft.class_332.method_51437(class_332.java:601)
	at net.minecraft.class_465.method_2380(class_465.java:178)
	at com.tom.storagemod.gui.AbstractStorageTerminalScreen.method_25394(AbstractStorageTerminalScreen.java:389)
	at com.tom.storagemod.gui.CraftingTerminalScreen.method_25394(CraftingTerminalScreen.java:130)
	at net.minecraft.class_437.method_47413(class_437.java:110)

-- Screen render details --
Details:
	Screen name: com.tom.storagemod.gui.CraftingTerminalScreen
	Mouse location: Scaled: (351, 283). Absolute: (1055.000000, 849.000000)
	Screen size: Scaled: (640, 360). Absolute: (1920, 1080). Scale factor of 3.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['HIRAPOT'/336, l='ClientLevel', x=72.88, y=63.00, z=-116.42]]
	Chunk stats: 225, 109
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,67,0), Section: (at 0,3,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 729193 game time, 272365 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:821)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, presencefootsteps:default_sound_pack, file/ichphilipp-s-endcity-vanilla-v1-1-1-18-1-e640.zip, file/Realistic Rain v1.0.0.zip

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 146986432 bytes (140 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx  
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: Zen / Zen+
	Frequency (GHz): 2.10
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: AMD Radeon(TM) Vega 8 Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x15d8
	Graphics card #0 versionInfo: DriverVersion=31.0.21905.1001
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 13228.16
	Virtual memory used (MB): 11365.65
	Swap memory total (MB): 7136.45
	Swap memory used (MB): 637.21
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		actual_cherries: Actual Cherries 1.0.0
		allarrowsinfinityfix: All Arrows Infinity Fix 1.4
		animal_feeding_trough: Animal Feeding Trough 1.1.0+1.20.1
		another_furniture: Another Furniture 1.20.1-3.0.1
		architectury: Architectury 9.2.14
		azurelib: AzureLib 2.0.21
		bakery: [Let's Do] Bakery 1.1.8
		balm-fabric: Balm 7.2.2
		beautify: Beautify 1.0.0+1.20
		bebooks: Better Enchanted Books 1.4.5
		better_climbing: Better Climbing 3
		better_katanas_fabric: Better Katanas [Fabric] 1.0.0
		bettermcdonaldsmod: Better McDonald's Mod 1.20.1-3.1.0
		carryon: Carry On 2.1.2.7
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		clutter: Clutter 1.20-0.5.7
		collective: Collective 7.40
		configured: Configured 2.2.3
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		coroutil: CoroUtil 1.20.1-1.3.7
		create: Create 0.5.1-f-build.1417+mc1.20.1
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.10-2
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_accessors: Porting Lib Accessors 2.3.2+1.20.1
				porting_lib_core: Porting Lib Core 2.3.2+1.20.1
			porting_lib_base: Porting Lib Base 2.3.2+1.20.1
				porting_lib_config: Porting Lib Config 2.3.2+1.20.1
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.2+1.20.1
				porting_lib_utility: Porting Lib Utility 2.3.2+1.20.1
			porting_lib_brewing: Porting Lib Brewing 2.3.2+1.20.1
			porting_lib_client_events: Porting Lib Client Events 2.3.2+1.20.1
			porting_lib_entity: Porting Lib Entity 2.3.2+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.2+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.3.2+1.20.1
				porting_lib_attributes: Porting Lib Attributes 2.3.2+1.20.1
				porting_lib_common: Porting Lib Common 2.3.2+1.20.1
			porting_lib_models: Porting Lib Models 2.3.2+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.2+1.20.1
			porting_lib_obj_loader: Porting Lib Obj Loader 2.3.2+1.20.1
				porting_lib_model_loader: Porting Lib Model Loader 2.3.2+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.2+1.20.1
			porting_lib_transfer: Porting Lib Transfer 2.3.2+1.20.1
				porting_lib_fluids: Porting Lib Fluids 2.3.2+1.20.1
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_gametest: Porting Lib GameTest 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		creativecore: CreativeCore 2.11.24
			net_minecraftforge_eventbus: eventbus 6.0.3
		croptopia: Croptopia 3.0.3
		deathchest: DeathChest 1.1
		dehydration: Dehydration 1.3.6
		diamond: Easy Diamond 1.20.1-1.6.4-[FABRIC]
		doapi: [Let's Do] API 1.2.9
			terraform-wood-api-v1: Terraform Wood API (v1) 7.0.1
		doubledoors: Double Doors 5.4
		dungeons_arise: When Dungeons Arise 2.1.57
		eldritch_mobs: EldritchMobs 1.15.1
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			polymer-blocks: Polymer (Textured Blocks) 0.5.15+1.20.1
			polymer-core: Polymer (Core) 0.5.15+1.20.1
				polymer-networking: Polymer (Networking) 0.5.15+1.20.1
					polymer-common: Polymer (Common) 0.5.15+1.20.1
				polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.5.15+1.20.1
			server_translations_api: Server Translations API 2.0.0+1.20
				packet_tweaker: Packet Tweaker 0.4.0+1.19.4
		ends_delight: End's Delight 1.0.1
		epherolib: EpheroLib 1.2.0
		epic_knights_japanese_armory: Epic Knights: Japanese Armory 1.6.2
		exposure: Exposure 1.5.1
		fabric-api: Fabric API 0.92.1+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+1802ada577
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabricloader: Fabric Loader 0.15.10
			mixinextras: MixinExtras 0.3.5
		fallingtree: FallingTree 4.3.4
		farmersdelight: Farmer's Delight 1.20.1-1.4.3
		farmingforblockheads: Farming for Blockheads 14.0.2
		forgeconfigapiport: Forge Config API Port 8.0.0
		fruitfulfun: Fruitful Fun 7.3.4
		geckolib: GeckoLib 4 4.4.4
			com_eliotlash_mclib_mclib: mclib 20
		hamsters: Hamsters fabric-1.0.3-1.20.1
		herbalbrews: [Let's Do] HerbalBrews 1.0.6
		highlighter: Highlighter 1.1.6
		iceberg: Iceberg 1.1.18
		immersive_aircraft: Immersive Aircraft 0.7.5+1.20.1
			org_mariuszgromada_math_mathparser_org-mxparser: MathParser.org-mXparser 5.2.1
		interactic: Interactic 0.2.0+1.20
		inventorio: Inventorio 1.10.3
			conditional-mixin: conditional mixin 0.6.2
		inventorysorter: Inventory Sorter 1.9.0-1.20
			kyrptconfig: Kyrpt Config 1.5.6-1.20
		itemonchest: Item On Chest 1.2.0
		itemphysic: ItemPhysic 1.7.1
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 15.3.0.4
		kiwi: Kiwi Library 11.6.2
		lambdynlights: LambDynamicLights 2.3.2+1.20.1
			pride: Pride Lib 1.2.0+1.19.4
			spruceui: SpruceUI 5.0.0+1.20
		lios_overhauled_villages: Lio's Overhauled Villages 1.18.2-1.20.4-v0.0.3
		logical_zoom: Logical Zoom 0.0.20
		lychee: Lychee Tweaker 5.1.11
		mcwdoors: Macaw's Doors 1.1.0
		meadow: [Let's Do] Meadow 1.3.8
		minecraft: Minecraft 1.20.1
		mobhealthbar: MobHealthBar 2.3.0
		mousetweaks: Mouse Tweaks 2.25
		nemos-carpentry: Nemo's Carpentry 2.3.1-1.20.1
		netherrackblasting: NetherrackBlasting 1.20.1-0-fabric
		owo: oωo 0.11.0+1.20
			blue_endless_jankson: jankson 1.2.2
		patchouli: Patchouli 1.20.1-84-FABRIC
			fiber: fiber 0.23.0-2
		presencefootsteps: Presence Footsteps 1.9.2
			kirin: Kirin UI 1.15.4+1.20
		puzzleslib: Puzzles Lib 8.1.18
			puzzlesaccessapi: Puzzles Access Api 8.0.7
		quickcraft: Quickcraft 1.2.5
		reevesfurniture: Reeves Furniture 1.1304
		sandwichable: Sandwichable 1.3.1+1.20.1
		sauces: Sauces 1.4.0
		thaumon: Thaumon [BETA] 2.2.0+1.20.1
		toms_storage: Tom's Simple Storage Mod 1.6.6
		travelersbackpack: Traveler's Backpack fabric-1.20.1-9.1.12
		universalenchants: Universal Enchants 8.0.0
			extensibleenums: Extensible Enums 7.0.1
		vc_gliders: Gliders 1.1.5
			palladiumcore: PalladiumCore 1.20-2.0.0.0
			player-animator: Player Animator 1.0.2-rc1+1.20
		vinery: [Let's Do] Vinery 1.4.14
		visualworkbench: Visual Workbench 8.0.0
		wafflesplaceablefoods: Waffle's Placeable Foods v1.3 Fabric 1.20.1
		walljump: Wall Jump 1.4.4
			fabric-language-kotlin: Fabric Language Kotlin 1.10.10+kotlin.1.9.10
				org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.10
				org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.10
				org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.10
				org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.10
				org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.22.0
				org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
				org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
				org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
				org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.0
				org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.0
				org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.0
			keybind_fix: Keybind Fix 1.0.0
			org_aeonbits_owner_owner: owner 1.0.12
		watut: What Are They Up To 1.20.1-1.1.1
		waystones: Waystones 14.1.3
		wildlife: Wildlife 1.19.2-2.2
		worthy_food: Worthy Food 1.3.0
		xaerominimap: Xaero's Minimap 24.2.0
		xaeroworldmap: Xaero's World Map 1.38.8
		xp_storage: XP Storage 1.5.3+1.20.1
			cardinal-components-item: Cardinal Components API (items) 5.2.1
	Flywheel Backend: GL33 Instanced Arrays
	Launched Version: fabric-loader-0.15.10-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: AMD Radeon(TM) Vega 8 Graphics GL version 3.2.0 Core Profile Context 23.11.1.231017, ATI Technologies Inc.
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, presencefootsteps:default_sound_pack, file/ichphilipp-s-endcity-vanilla-v1-1-1-18-1-e640.zip (incompatible), file/Realistic Rain v1.0.0.zip (incompatible)
	Current Language: en_us
	CPU: 8x AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx 
	Server Running: true
	Player Count: 1 / 8; [class_3222['HIRAPOT'/336, l='ServerLevel[...]', x=72.88, y=63.00, z=-116.42]]
	Data Packs: vanilla, fabric, fruitfulfun:farmersdelight_nhoryzon, fruitfulfun:food, fruitfulfun:apple_tree_in_village
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable

**Comment by Fourmisain** [comment]
`NoClassDefFoundError: net/minecraft/class_8828$class_2585` (`class_8828$class_2585` = `PlainTextContent$Literal`)
seems to suggest you're running an incompatible Better Enchanted Books version for your Minecraft version.

Hm... the log says
Better Enchanted Books 1.4.5
Minecraft 1.20.1
and according to Modrinth that version is marked compatible, so maybe we messed something up there.

**Comment by Fourmisain** [comment]
Ah yeah, this changed in 7e96ab7f951308ee2f2556fffbb4a8cff9193edf, 1.4.4+ is only compatible with Minecraft ~~1.20.4+~~ 1.20.3+.

1.4.3 is the last version compatible with 1.20.1 it looks like.

**Comment by Fourmisain** [comment]
It's a bit weird since `getContent` should usually not be called in vanilla, so it's sorta compatible but not really.
(At least I didn't catch any errors in my previous testing for #65.)
From the stacktrace, it's appears to be called from Iceberg, which Highlighter uses, so that seems to confirm that.

@Bernasss12 Can you update the version range on Modrinth/CF?
1.4.3 is compatible with 1.20 - 1.20.2
1.4.4/5 with 1.20.3/4
The Kotlin betas up to 2.0.3 should be changed to 1.20.3/4 as well.

Also, the code should be using `PlainTextContent.EMPTY` there, if that's still relevant.

Sad it's not backwards compatible, but in the end it's only the quickplay fix and a translation, I think, otherwise 1.4.3 should be fine.

**Comment by Bernasss12** [comment]
Will do 👍🏻

**Comment by N1zle** [comment]
Maybe a weird necro but 1.4.3 is still not marked as 1.20.1/2 compatible (on Modrinth). Important for the mod, considering 1.20.1 is still a major version for the modding scene.
