### ISSUE TITLE
[Feature Request] Update plans for Minecraft version 1.21.x?

### ISSUE THREAD

**Issue by Abbanon** [Bernasss12/BetterEnchantedBooks#72]
It would be great if this mod is within your scope for eventual 1.21.x updates.
As-is, it sadly isn't compatible.

**Comment by Bernasss12** [comment]
I mostly updated it locally but wasn't entirely happy with the state of the code so I haven't published anything yet. This made me kinda unmotivated to work on this for a while but I do plan to finish the update soonish™️

**Comment by Bernasss12** [comment]
Sorry it took so long but I finally got the motivation to cleanup the mess I left when I last touched this code :S

I'm releasing this in beta and I do believe there might be some problems hopefully enough people use it so I can fix everything asap

Thank you for being patient 

Edit: this means I have just uploaded a new version to Modrinth and Curseforge, when they'll be live depends on each platform ofc
