### ISSUE TITLE
[Bug] Can't disable enchanted books being colored by the mod.

### ISSUE THREAD

**Issue by Arrowpuppet** [Bernasss12/BetterEnchantedBooks#74]
**Describe the bug**
Disabling the book coloring in the config does not disable the book coloring.

**To Reproduce**
Disable book coloring in the config.

**Expected behavior**
Book coloring is disabled.

**Please include:**
 - Minecraft Version: 1.20.6
 - Mod Version 2.0.5-beta
 - Cloth Config v14.0.139, Fabric API v0.100.8+1.20.6, Fabric Language Kotlin 1.12.2+kotlin.2.0.20

**Comment by Bernasss12** [comment]
Uploaded a fix to Modrinth and Curseforge
