### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by dexman545** [Bernasss12/BetterEnchantedBooks#9]
MC 20w12a
Latest FAPI and BEB from curseforge.

Log: https://gist.github.com/dexman545/9824bcabb7d898623ce2b2c8990f5d12

**Comment by Bernasss12** [comment]
My bad I ended up not porting the mod to the latest versions, I will do it shortly.

**Comment by Bernasss12** [comment]
Uploaded to CurseForge should be done processing eventually, have fun!
If it was fixed please close this issue :)
